### ISSUE TITLE
Update shebang

### ISSUE THREAD

**Issue by luisc009** [pschoffer/huset-priser#12]
Hi pschoffer! 

Consider to use `#!/usr/bin/env bash` as Shebang as it adds more portability to your scripts, you can take a look to the an [NixCraft](https://www.cyberciti.biz/tips/finding-bash-perl-python-portably-using-env.html).

**Comment by pschoffer** [comment]
Sounds great! I'll do that. Thanks a lot for the input!

**Comment by pschoffer** [comment]
Done!
